#############################################################################
# Makefile for building: Outgoing-Packet-Tool
# Generated by qmake (2.01a) (Qt 4.7.4) on: Thu Nov 10 15:28:18 2011
# Project:  Outgoing-Packet-Tool.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.7.4/bin/qmake -o Makefile Outgoing-Packet-Tool.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++-64 -I. -I/usr/local/Trolltech/Qt-4.7.4/include/QtCore -I/usr/local/Trolltech/Qt-4.7.4/include/QtGui -I/usr/local/Trolltech/Qt-4.7.4/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.7.4/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.7.4/lib -ldl -lpcap -lQtGui -L/usr/local/Trolltech/Qt-4.7.4/lib -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.7.4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = globals.cpp \
		main-window.cpp \
		central-window.cpp \
		main.cpp \
		packet-sniffer.cpp \
		packet-sieve.cpp \
		train-dialog.cpp \
		write-dialog.cpp \
		delete-dialog.cpp moc_main-window.cpp \
		moc_central-window.cpp \
		moc_train-dialog.cpp \
		moc_write-dialog.cpp \
		moc_delete-dialog.cpp \
		qrc_application.cpp
OBJECTS       = globals.o \
		main-window.o \
		central-window.o \
		main.o \
		packet-sniffer.o \
		packet-sieve.o \
		train-dialog.o \
		write-dialog.o \
		delete-dialog.o \
		moc_main-window.o \
		moc_central-window.o \
		moc_train-dialog.o \
		moc_write-dialog.o \
		moc_delete-dialog.o \
		qrc_application.o
DIST          = /usr/local/Trolltech/Qt-4.7.4/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/include_source_dir.prf \
		Outgoing-Packet-Tool.pro
QMAKE_TARGET  = Outgoing-Packet-Tool
DESTDIR       = 
TARGET        = Outgoing-Packet-Tool

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Outgoing-Packet-Tool.pro  /usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++-64/qmake.conf /usr/local/Trolltech/Qt-4.7.4/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.7.4/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.7.4/lib/libQtCore.prl
	$(QMAKE) -o Makefile Outgoing-Packet-Tool.pro
/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.7.4/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.7.4/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Outgoing-Packet-Tool.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Outgoing-Packet-Tool1.0.0 || $(MKDIR) .tmp/Outgoing-Packet-Tool1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Outgoing-Packet-Tool1.0.0/ && $(COPY_FILE) --parents main-window.h central-window.h packet-sniffer.h packet-sieve.h train-dialog.h write-dialog.h delete-dialog.h .tmp/Outgoing-Packet-Tool1.0.0/ && $(COPY_FILE) --parents application.qrc .tmp/Outgoing-Packet-Tool1.0.0/ && $(COPY_FILE) --parents globals.cpp main-window.cpp central-window.cpp main.cpp packet-sniffer.cpp packet-sieve.cpp train-dialog.cpp write-dialog.cpp delete-dialog.cpp .tmp/Outgoing-Packet-Tool1.0.0/ && (cd `dirname .tmp/Outgoing-Packet-Tool1.0.0` && $(TAR) Outgoing-Packet-Tool1.0.0.tar Outgoing-Packet-Tool1.0.0 && $(COMPRESS) Outgoing-Packet-Tool1.0.0.tar) && $(MOVE) `dirname .tmp/Outgoing-Packet-Tool1.0.0`/Outgoing-Packet-Tool1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Outgoing-Packet-Tool1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_main-window.cpp moc_central-window.cpp moc_train-dialog.cpp moc_write-dialog.cpp moc_delete-dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_main-window.cpp moc_central-window.cpp moc_train-dialog.cpp moc_write-dialog.cpp moc_delete-dialog.cpp
moc_main-window.cpp: main-window.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) main-window.h -o moc_main-window.cpp

moc_central-window.cpp: central-window.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) central-window.h -o moc_central-window.cpp

moc_train-dialog.cpp: train-dialog.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) train-dialog.h -o moc_train-dialog.cpp

moc_write-dialog.cpp: write-dialog.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) write-dialog.h -o moc_write-dialog.cpp

moc_delete-dialog.cpp: delete-dialog.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) delete-dialog.h -o moc_delete-dialog.cpp

compiler_rcc_make_all: qrc_application.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_application.cpp
qrc_application.cpp: application.qrc \
		images/new.png \
		images/copy.png \
		images/cut.png \
		images/save.png \
		images/paste.png \
		images/open.png
	/usr/local/Trolltech/Qt-4.7.4/bin/rcc -name application application.qrc -o qrc_application.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

globals.o: globals.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o globals.o globals.cpp

main-window.o: main-window.cpp main-window.h \
		central-window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main-window.o main-window.cpp

central-window.o: central-window.cpp central-window.h \
		train-dialog.h \
		write-dialog.h \
		delete-dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o central-window.o central-window.cpp

main.o: main.cpp main-window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

packet-sniffer.o: packet-sniffer.cpp globals.h \
		packet-sieve.h \
		definitions.h \
		packet-sniffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o packet-sniffer.o packet-sniffer.cpp

packet-sieve.o: packet-sieve.cpp packet-sieve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o packet-sieve.o packet-sieve.cpp

train-dialog.o: train-dialog.cpp train-dialog.h \
		packet-sniffer.h \
		definitions.h \
		globals.h \
		packet-sieve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o train-dialog.o train-dialog.cpp

write-dialog.o: write-dialog.cpp globals.h \
		write-dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o write-dialog.o write-dialog.cpp

delete-dialog.o: delete-dialog.cpp globals.h \
		delete-dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o delete-dialog.o delete-dialog.cpp

moc_main-window.o: moc_main-window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main-window.o moc_main-window.cpp

moc_central-window.o: moc_central-window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_central-window.o moc_central-window.cpp

moc_train-dialog.o: moc_train-dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_train-dialog.o moc_train-dialog.cpp

moc_write-dialog.o: moc_write-dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_write-dialog.o moc_write-dialog.cpp

moc_delete-dialog.o: moc_delete-dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_delete-dialog.o moc_delete-dialog.cpp

qrc_application.o: qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_application.o qrc_application.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

