######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 4 16:13:54 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input

HEADERS += main-window.h central-window.h functions.h packet-sieve.h
SOURCES += globals.cpp main-window.cpp central-window.cpp main.cpp functions.cpp packet-sieve.cpp
RESOURCES = application.qrc
LIBS += -ldl -lpcap
